import type { Metadata } from 'next'

import './globals.css'
import NextAuthProvider from '@/contexts/NextAuthProvider'
import WalletProvider from '@/contexts/WalletProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="w-full h-full bg-white dark:bg-stone-950 overscroll-none">
        <NextAuthProvider>
          <WalletProvider>
            <div className="mt-8">
              {children}
            </div>
          </WalletProvider>
        </ NextAuthProvider>
      </body>
    </html>
  )
}
