import type { Metadata } from "next";

import ClientProvider from "@/contexts/ClientProvider";
import NextAuthProvider from "@/contexts/NextAuthProvider";

import "./globals.css";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="w-full h-full bg-white dark:bg-stone-950 overscroll-none">
        <NextAuthProvider>
          <ClientProvider>
            <div className="mt-8">{children}</div>
          </ClientProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
