import type { Metadata } from 'next'

import './globals.css'
import NextAuthProvider from '@/contexts/NextAuthProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="w-full h-full bg-white dark:bg-stone-950 overscroll-none">
        <NextAuthProvider>
          {children}
        </ NextAuthProvider>
      </body>
    </html>
  )
}
