package actions

const (
	TypeAction     string = "action"
	TypeConstraint string = "constraint"

	Plug      string = "plug"
	Boolean   string = "boolean"
	AaveV3    string = "aave_v3"
	YearnV3   string = "yearn_v3"
	Nouns     string = "nouns"
	ENS       string = "ens"
	Morpho    string = "morpho"
	Bebop     string = "bebop"
	Euler     string = "euler"
	Math      string = "math"
	Scripting string = "scripting"

	ActionDeposit      string = "deposit"
	ActionBorrow       string = "borrow"
	ActionRedeem       string = "redeem"
	ActionRedeemMax    string = "redeem_max"
	ActionWithdraw     string = "withdraw"
	ActionWithdrawMax  string = "withdraw_max"
	ActionRepay        string = "repay"
	ActionHarvest      string = "harvest"
	ActionTransfer     string = "transfer"
	ActionTransferFrom string = "transfer_from"
	ActionApprove      string = "approve"
	ActionSwap         string = "swap"
	ActionRoute        string = "route"
	ActionStake        string = "stake"
	ActionStakeMax     string = "stake_max"
	ActionBuy          string = "buy"
	ActionBid          string = "bid"
	ActionRenew        string = "renew"

	ConstraintHealthFactor       string = "health_factor"
	ConstraintAPY                string = "apy"
	ConstraintAPYDifferential    string = "apy_differential"
	ConstraintAvailableLiquidity string = "available_liquidity"
	ConstraintTimeLeft           string = "time_left"
	ConstraintPrice              string = "price"
	ConstraintBalance            string = "balance"
)
