package actions

const (
	TypeAction     string = "action"
	TypeConstraint string = "constraint"

	AaveV3    string = "aave_v3"
	Assert    string = "assert"
	BasePaint string = "basepaint"
	Bebop     string = "bebop"
	Boolean   string = "boolean"
	Database  string = "database"
	ENS       string = "ens"
	Euler     string = "euler"
	Math      string = "math"
	Morpho    string = "morpho"
	Nouns     string = "nouns"
	Plug      string = "plug"
	Scripting string = "scripting"
	YearnV3   string = "yearn_v3"

	ActionDeposit      string = "deposit"
	ActionBorrow       string = "borrow"
	ActionRedeem       string = "redeem"
	ActionWithdraw     string = "withdraw"
	ActionRepay        string = "repay"
	ActionHarvest      string = "harvest"
	ActionTransfer     string = "transfer"
	ActionTransferFrom string = "transfer_from"
	ActionApprove      string = "approve"
	ActionSwap         string = "swap"
	ActionRoute        string = "route"
	ActionStake        string = "stake"
	ActionBuy          string = "buy"
	ActionBid          string = "bid"
	ActionRenew        string = "renew"
	ActionMint         string = "mint"

	ConstraintHealthFactor       string = "health_factor"
	ConstraintAPY                string = "apy"
	ConstraintAPYDifferential    string = "apy_differential"
	ConstraintAvailableLiquidity string = "available_liquidity"
	ConstraintTimeLeft           string = "time_left"
	ConstraintPrice              string = "price"
	ConstraintBalance            string = "balance"

	ReadBalance      string = "balance"
	ReadPrice        string = "price"
	ReadAPY          string = "apy"
	ReadHealthFactor string = "health_factor"
)
