[profile.default]
    src = "src"
    out = "artifacts"
    libs = ["lib"]
    remappings = [
        "@prb/test/=lib/prb-test/src/",
        "op/=lib/interop-lib/src/",
        "forge-std/=lib/forge-std/src/",
        "solady/=node_modules/solady/src/",
    ]
    block_timestamp = 1_680_220_800
    bytecode_hash = "none"
    evm_version = "paris"
    fuzz = { runs = 10_000 }
    gas_reports = ["*"]
    optimizer = true
    optimizer_runs = 10_000
    via_ir = true
    script = "src/contracts/script"
    solc = "0.8.26"

[profile.ci]
    fuzz = { runs = 10_000 }
    verbosity = 4

[etherscan]
    base = { key = "${ETHERSCAN_API_KEY}" }
    mainnet = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
    base = "https://${QUICKNODE_NAME}.base-mainnet.quiknode.pro/${QUICKNODE_API_KEY}"
    base_sepolia = "https://${QUICKNODE_NAME}.base-sepolia.quiknode.pro/${QUICKNODE_API_KEY}"
    localhost = "http://localhost:8545"
    mainnet = "https://${QUICKNODE_NAME}.quiknode.pro/${QUICKNODE_API_KEY}"
    sepolia = "https://${QUICKNODE_NAME}.ethereum-sepolia.quiknode.pro/${QUICKNODE_API_KEY}"

[fmt]
    bracket_spacing = true
    int_types = "long"
    multiline_func_header = "all"
    number_underscore = "thousands"
    quote_style = "double"
    tab_width = 4
    wrap_comments = false
    line_length=80

