import type { Metadata } from 'next'
import { PropsWithChildren } from 'react'

import Hud from './components/Hud'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Layout({
  children,
}: PropsWithChildren) {
  return (
    <Hud>
      {children}
    </Hud>
  )
}
