version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: plug_solver_postgres
    environment:
      POSTGRES_USER: plug
      POSTGRES_PASSWORD: plugdev
      POSTGRES_DB: plug_solver
    ports:
      - "6432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U plug"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 