services:
  # Database and cache services
  postgres:
    image: postgres:16-alpine
    container_name: plug_solver_postgres
    environment:
      DATABASE_USER: plug
      DATABASE_PASSWORD: plugdev
      DATABASE_DB: plug_solver
    ports:
      - "6432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U plug"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: plug_solver_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
